version: "3.1"

services:
  aoi-ros2:
    container_name: aoi-ros2
    profiles: [inspection]
    image: aoi-ros2:latest 
    restart: always
    volumes:
      - aoi-main:/aoi  # For production
    build:
      context: .
      dockerfile: dockerfile.aoi-ros2
    expose:
      - 9090  # Ros2 bridge websocket server
  aoi-mysql:
    container_name: aoi-mysql
    profiles: [core, inspection]
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 8081:3306
  aoi-adminer:
    container_name: aoi-adminer
    profiles: [core, inspection]
    image: adminer
    restart: always
    depends_on:
      - aoi-mysql
    ports:
      - 8080:8080
volumes:
  aoi-main:
