FROM ros:foxy-ros-base

WORKDIR /aoi/open_aoi_ros
COPY open_aoi_ros /aoi/open_aoi_ros

# Colcon
RUN apt install python3-colcon-common-extensions
# Ros2 bridge for external communication (web interface)
RUN apy isntall ros-foxy-rosbridge-*
RUN bash aoi.build.bash

CMD ["bash", "aoi.launch.bash"]